#!/bin/bash -eu

echo "Compiling..."

rm -rf build/*
mkdir -p build

node_modules/.bin/tdi -q # not everyone has the latest npm

npm run eslint
npm run prettify-check

echo "Compiling PEG.js"
./compile-pegjs

echo "Compiling TypeScript"
./compile-tsc
