#!/bin/bash

mkdir -p build

node_modules/.bin/tsc --noImplicitAny --noEmitOnError --declaration --removeComments --noFallthroughCasesInSwitch --noImplicitReturns --out build/plywood.js \
  src/init.ts \
  \
  src/dialect/baseDialect.ts \
  src/dialect/mySqlDialect.ts \
  src/dialect/postgresDialect.ts \
  \
  src/datatypes/common.ts \
  src/datatypes/attributeInfo.ts \
  src/datatypes/range.ts \
  src/datatypes/numberRange.ts \
  src/datatypes/set.ts \
  src/datatypes/timeRange.ts \
  src/datatypes/dataset.ts \
  src/datatypes/external.ts \
  \
  src/external/druidExternal.ts \
  src/external/sqlExternal.ts \
  src/external/mySqlExternal.ts \
  src/external/postgresExternal.ts \
  \
  src/expressions/baseExpression.ts \
  src/expressions/literalExpression.ts \
  src/expressions/refExpression.ts \
  src/expressions/externalExpression.ts \
  src/expressions/chainExpression.ts \
  \
  src/actions/baseAction.ts \
  src/actions/absoluteAction.ts \
  src/actions/addAction.ts \
  src/actions/andAction.ts \
  src/actions/applyAction.ts \
  src/actions/averageAction.ts \
  src/actions/baseAction.ts \
  src/actions/concatAction.ts \
  src/actions/containsAction.ts \
  src/actions/countAction.ts \
  src/actions/countDistinctAction.ts \
  src/actions/customAction.ts \
  src/actions/divideAction.ts \
  src/actions/extractAction.ts \
  src/actions/fallbackAction.ts \
  src/actions/filterAction.ts \
  src/actions/greaterThanAction.ts \
  src/actions/greaterThanOrEqualAction.ts \
  src/actions/inAction.ts \
  src/actions/isAction.ts \
  src/actions/joinAction.ts \
  src/actions/lessThanAction.ts \
  src/actions/lessThanOrEqualAction.ts \
  src/actions/lookupAction.ts \
  src/actions/limitAction.ts \
  src/actions/matchAction.ts \
  src/actions/maxAction.ts \
  src/actions/minAction.ts \
  src/actions/multiplyAction.ts \
  src/actions/notAction.ts \
  src/actions/numberBucketAction.ts \
  src/actions/orAction.ts \
  src/actions/overlapAction.ts \
  src/actions/powerAction.ts \
  src/actions/quantileAction.ts \
  src/actions/selectAction.ts \
  src/actions/sortAction.ts \
  src/actions/splitAction.ts \
  src/actions/substrAction.ts \
  src/actions/subtractAction.ts \
  src/actions/sumAction.ts \
  src/actions/timeBucketAction.ts \
  src/actions/timeFloorAction.ts \
  src/actions/timePartAction.ts \
  src/actions/timeRangeAction.ts \
  src/actions/timeShiftAction.ts \
  \
  src/executor/basicExecutor.ts \
  \
  src/helper/simpleLocator.ts \
  src/helper/verboseRequester.ts \
  src/helper/retryRequester.ts \
  src/helper/concurrentLimitRequester.ts \
  src/helper/promiseWhile.ts \
  src/helper/utils.ts \
  \
  src/exports.ts \
  && \
  node extra/extra.js;
