#!/bin/bash -eu

echo "Compiling..."

rm -rf build/*
mkdir -p build

node_modules/.bin/tdi -q # not everyone has the latest npm

echo "Compiling PEG.js"
./compile-pegjs

echo "Compiling TypeScript"
./compile-tsc

echo "Compiling package"
./compile-package

echo "Minifying"
node_modules/.bin/uglifyjs package/plywood.js -o package/plywood.min.js
node_modules/.bin/uglifyjs package/plywood-lite.js -o package/plywood-lite.min.js
