// Generated by dts-bundle v0.2.0

declare module HigherObject {
    export interface Base {
      /**
       * Checks to see if thing is an instance of the given constructor.
       * Works just like the native instanceof method but handles the case when
       * objects are coming from different frames or from different modules.
       * @param thing - the thing to test
       * @param constructor - the constructor class to check against
       * @returns {boolean}
       */
        isInstanceOf(thing: any, constructor: any): boolean;
      /**
       * Check to see if things are an array of instances of the given constructor
       * Uses isInstanceOf internally
       * @param things - the array of things to test
       * @param constructor - the constructor class to check against
       * @returns {boolean}
       */
        isArrayOf(things: any[], constructor: any): boolean;
      /**
       * Does a quick 'duck typing' test to see if the given parameter is a Higher Object
       * @param thing - the thing to test
       * @returns {boolean}
       */
        isHigherObject(thing: any): boolean;
      /**
       * Checks is two arrays have equal higher objects
       * @param arrayA - array to compare
       * @param arrayB - array to compare
       * @returns {boolean}
       */
        arraysEqual<T>(arrayA: T[], arrayB: T[]): boolean;
      /**
       * Interface that the Higher Object class should extend (types the instance)
       */
    }
        export interface ImmutableInstance<ValueType, JSType> {
          valueOf(): ValueType;
          toJS(): JSType;
          toJSON(): JSType;
          equals(other: ImmutableInstance<ValueType, JSType>): boolean;
        }

    /**
        * Interface that the Higher Object class should conform to (types the class)
        */
    export interface ImmutableClass<ValueType, JSType> {
            fromJS(properties: JSType): ImmutableInstance<ValueType, JSType>;
            new (properties: ValueType): any;
    }
}

declare var HigherObject: HigherObject.Base;

declare module 'higher-object' {
  export = HigherObject;
}