#!/bin/bash -e

docker-machine start default || echo "Machine is already running";
eval $(docker-machine env)

echo "Resetting to base state"
docker rm -f plywood-test-mysql 2>/dev/null || echo "no MySQL container to remove";
docker rm -f plywood-test-druid 2>/dev/null || echo "no Druid container to remove";

echo "Loading Druid..."
docker build -t plywood-test-druid "${IMPLY_PROJECTS}/plywood/data/druid"
docker run -v "${IMPLY_PROJECTS}/plywood/data":/opt/data -p 8081-8110:8081-8110 -p 8200:8200 -p 9095:9095 -d --name plywood-test-druid plywood-test-druid
docker exec -it plywood-test-druid /opt/data/druid/load-data

echo "Loading MySQL..."
docker run -v "${IMPLY_PROJECTS}/plywood/data":/opt/data -p 3306:3306 -d --name plywood-test-mysql -e MYSQL_ALLOW_EMPTY_PASSWORD='true' -d mysql/mysql-server:5.7
docker exec -it plywood-test-mysql /opt/data/mysql/load-data
