#!/bin/bash -e

# Move this to TSD
echo "Updating druid.d.ts..."

rm -rf node_modules/druid.d.ts

npm install druid.d.ts@latest
mkdir -p typings/druid
cp -r node_modules/druid.d.ts/druid/druid.d.ts typings/druid/druid.d.ts

rm -rf node_modules/druid.d.ts
