#!/bin/bash -eu
echo "setting up mysql";
mysql -uroot -e "create database plywood_test; 
			CREATE USER 'plywood_user' IDENTIFIED BY 'HadleyWickham';
			GRANT ALL ON plywood_test.* TO 'plywood_user';"
echo "importing data";
mysql -u root plywood_test < /opt/data/wikipedia-defs.sql; 
mysql -u root plywood_test < /opt/data/wikipedia.sql;
