#!/bin/bash -eu
echo "json to values list"

cat wikipedia.json \
| jq -c -r ' 
. | { 
	time: .time | sub(":00Z"; ":00"), 
	sometimeLater: .sometimeLater | sub(":00Z"; ":00"),
	channel,
	cityName,
	comment,
	commentLength,
	countryIsoCode,
	countryName,
	isAnonymous,
	isMinor,
	isNew,
	isRobot,
	isUnpatrolled,
	metroCode,
	namespace,
	page,
	regionIsoCode,
	regionName,
	user,
	userChars: .userChars | map(. | sub("'\''"; "\\''")),
	delta,
	added,
	deleted,
	deltaByTen
	} 
| [
	.time, 
	.sometimeLater, 
	.channel,
	.cityName,
	.comment,
	.commentLength,
	.countryIsoCode,
	.countryName,
	.isAnonymous,
	.isMinor,
	.isNew,
	.isRobot,
	.isUnpatrolled,
	.metroCode,
	.namespace,
	.page,
	.regionIsoCode,
	.regionName,
	.user,
	.userChars,
	.delta,
	.added,
	.deleted,
	.deltaByTen 
	] ' \
  > wikipedia.txt

echo "values list to sql statements";
# breaking up insert statements becuase mysql server seems to 'go away' otherwise

sed -e 's/^\[/(/g' \
 	-e "s/,\[\"/,\'\[\"/g" \
 	-e "s/\"\],/\"\]\',/g" \
 	-e 's/]$/),/g' \
 	-e '$s/),/);/' \
	-e '0~10 s/,$/; INSERT INTO wikipedia values/g' \
	-e '1iINSERT INTO wikipedia values' \
 	wikipedia.txt > wikipedia.sql


