#!/bin/bash -eu

# Force this to the working directory
cd "$(dirname "$0")"

rm -rf tmp
mkdir tmp

# Trim milliseconds for time and seconds for some time later
echo "Extracting and transforming...";
gzcat wikipedia-2015-09-12.gz \
  | jq -c '
    select("2015-09-12" < .timestamp and .timestamp < "2015-09-13") |
    {
      time: .timestamp | sub(".[0-9]{3}Z"; "Z"),
      sometimeLater: .timestamp | sub("2015-"; "2016-") | sub(":[0-9]{2}.[0-9]{3}Z"; ":00Z"),
      channel: .channel | sub("#"; "") | sub(".wikipedia"; ""),
      cityName,
      comment,
      commentLength: .comment | length,
      countryIsoCode,
      countryName,
      isAnonymous: (.countryName != null),
      isMinor,
      isNew,
      isRobot,
      isUnpatrolled,
      metroCode,
      namespace,
      page,
      regionIsoCode,
      regionName,
      user,
      userChars: .user | ascii_upcase | split("") | unique,
      delta,
      added: [.delta, 0] | max,
      deleted: [-.delta, 0] | max,
      deltaByTen: (.delta / 10)
    }' \
  > tmp/wikipedia.json

echo "Sampling...";
perl -ne'print if $. % 10 == 0' tmp/wikipedia.json > tmp/wikipedia-sampled.json

./make-sql
