#!/bin/bash -eu

# Force this to the working directory
cd "$(dirname "$0")"

echo "Converting JSON to SQL inserts"

echo "SELECT 'Do this' AS Lets" > tmp/wikipedia-raw.sql;

cat tmp/wikipedia.json \
| jq -c -r '
  {
    time: .time | sub("Z"; ""),
    sometimeLater: .sometimeLater | sub("Z"; ""),
    channel,
    cityName,
    comment,
    commentLength,
    countryIsoCode,
    countryName,
    isAnonymous,
    isMinor,
    isNew,
    isRobot,
    isUnpatrolled,
    metroCode,
    namespace,
    page,
    regionIsoCode,
    regionName,
    user,
    delta,
    added,
    deleted,
    deltaByTen
	}
  |
  [
    .time,
    .sometimeLater,
    .channel,
    .cityName,
    .comment,
    .commentLength,
    .countryIsoCode,
    .countryName,
    .isAnonymous,
    .isMinor,
    .isNew,
    .isRobot,
    .isUnpatrolled,
    .metroCode,
    .namespace,
    .page,
    .regionIsoCode,
    .regionName,
    .user,
    .delta,
    .added,
    .deleted,
    .deltaByTen
  ]
  | tostring
  | .[1:-1]
  | ((if (input_line_number - 1) % 100 == 0 then "; INSERT INTO wikipedia_raw VALUES (" else ", (" end) + . + ")")
' >> tmp/wikipedia-raw.sql

echo ";" >> tmp/wikipedia-raw.sql;
