#!/bin/bash -eu

echo "Sleep for 15 seconds to make sure the server starts";
sleep 15;

echo "Setting up MySQL...";
mysql -u root -e "CREATE DATABASE IF NOT EXISTS plywood_test CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"

echo "Creating table...";
mysql -u root plywood_test < /opt/data/mysql/wikipedia-create-raw-table.sql;

echo "Importing data...";
mysql -u root --default_character_set utf8mb4 plywood_test < /opt/data/tmp/wikipedia-raw.sql;

echo "Rolling up...";
mysql -u root plywood_test < /opt/data/mysql/wikipedia-rollup.sql;

echo "Done";
